// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function ConnectSpotify(arg1) {
  return window['go']['main']['App']['ConnectSpotify'](arg1);
}

export function DetectLocation() {
  return window['go']['main']['App']['DetectLocation']();
}

export function DisconnectSpotify() {
  return window['go']['main']['App']['DisconnectSpotify']();
}

export function ExportAnnualBook(arg1) {
  return window['go']['main']['App']['ExportAnnualBook'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetCurrentTrack() {
  return window['go']['main']['App']['GetCurrentTrack']();
}

export function GetCurrentWeather() {
  return window['go']['main']['App']['GetCurrentWeather']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetHeatmapData() {
  return window['go']['main']['App']['GetHeatmapData']();
}

export function GetInsights() {
  return window['go']['main']['App']['GetInsights']();
}

export function GetListeningByDayOfWeek(arg1) {
  return window['go']['main']['App']['GetListeningByDayOfWeek'](arg1);
}

export function GetListeningByHour(arg1) {
  return window['go']['main']['App']['GetListeningByHour'](arg1);
}

export function GetMoodDistribution(arg1, arg2) {
  return window['go']['main']['App']['GetMoodDistribution'](arg1, arg2);
}

export function GetSessionTracks(arg1) {
  return window['go']['main']['App']['GetSessionTracks'](arg1);
}

export function GetSessionsByDate(arg1) {
  return window['go']['main']['App']['GetSessionsByDate'](arg1);
}

export function GetSessionsByMonth(arg1, arg2) {
  return window['go']['main']['App']['GetSessionsByMonth'](arg1, arg2);
}

export function GetTopArtists(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopArtists'](arg1, arg2, arg3);
}

export function GetTopTracks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTopTracks'](arg1, arg2, arg3);
}

export function GetWeatherCorrelation(arg1) {
  return window['go']['main']['App']['GetWeatherCorrelation'](arg1);
}

export function GetYearStats(arg1) {
  return window['go']['main']['App']['GetYearStats'](arg1);
}

export function GetYearsWithData() {
  return window['go']['main']['App']['GetYearsWithData']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsSpotifyConnected() {
  return window['go']['main']['App']['IsSpotifyConnected']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetSessionMood(arg1, arg2) {
  return window['go']['main']['App']['SetSessionMood'](arg1, arg2);
}

export function UpdateLocationFromCoords(arg1, arg2) {
  return window['go']['main']['App']['UpdateLocationFromCoords'](arg1, arg2);
}
