// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {diary} from '../models';
import {player} from '../models';
import {weather} from '../models';

export function CompleteOnboarding():Promise<void>;

export function ConnectSpotify(arg1:string):Promise<void>;

export function DetectLocation():Promise<Record<string, any>>;

export function DisconnectSpotify():Promise<void>;

export function ExportAnnualBook(arg1:number):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentSession():Promise<diary.Session>;

export function GetCurrentTrack():Promise<player.TrackInfo>;

export function GetCurrentWeather():Promise<weather.Data>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetHeatmapData():Promise<Array<diary.DailyStats>>;

export function GetInsights():Promise<Array<diary.Insight>>;

export function GetListeningByDayOfWeek(arg1:number):Promise<Array<diary.DayOfWeekStat>>;

export function GetListeningByHour(arg1:number):Promise<Array<diary.HourStat>>;

export function GetMoodDistribution(arg1:string,arg2:string):Promise<Array<diary.MoodStat>>;

export function GetSessionTracks(arg1:string):Promise<Array<diary.SessionTrack>>;

export function GetSessionsByDate(arg1:string):Promise<Array<diary.Session>>;

export function GetSessionsByMonth(arg1:number,arg2:number):Promise<Array<diary.Session>>;

export function GetTopArtists(arg1:number,arg2:number,arg3:number):Promise<Array<diary.ArtistStats>>;

export function GetTopTracks(arg1:number,arg2:number,arg3:number):Promise<Array<diary.TrackStats>>;

export function GetWeatherCorrelation(arg1:number):Promise<Array<diary.WeatherStat>>;

export function GetYearStats(arg1:number):Promise<Record<string, any>>;

export function GetYearsWithData():Promise<Array<number>>;

export function IsFirstRun():Promise<boolean>;

export function IsSpotifyConnected():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetSessionMood(arg1:string,arg2:string):Promise<void>;

export function UpdateLocationFromCoords(arg1:number,arg2:number):Promise<void>;
